chat/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'chat.views.home', name='home'),
    url(r'^node_api$', 'chat.views.node_api', name='node_api'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

core/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='home'),

    url(r'^calendar/$', views.view_calendar, name='view_calendar'),
    url(r'^no-calendar-guide/$', views.no_calendar_guide, name='no_calendar_guide'),

    url(r'^search/tag/', views.search_study_group_with_tag, name='search_study_group_with_tag'),
    url(r'^search/', views.search_study_group, name='search_study_group'),
    url(r'^help/$', views.view_help, name='view_help'),

    url(r'^create/$', views.create_study_group, name='create_study_group'),
    url(r'^(?P<study_group_id>\w+)/delete/$', views.delete_study_group, name='delete_study_group'),
    url(r'^join/$', views.join_study_group, name='join_study_group'),
    url(r'^like/$', views.like_study_group, name='like_study_group'),

    url(r'^(?P<study_group_id>\w+)/$', views.view_study_group, name='view_study_group'),

    url(r'^group/board/edit/$', include('django_summernote.urls')),

    url(r'^articles/comments/', include('django.contrib.comments.urls')),
)

event/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

)

studyplan/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from core import views as c_views
from board import views as b_views
from event import views as e_views
from file import views as f_views

STUDY = r'^s/(?P<study_group_id>\w+)/'

BOARD = STUDY + r'board/'
EVENT = STUDY + r'event/'
FILE = STUDY + r'file/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'core.views.index'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    #(r'^asset/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.ASSET_ROOT}),

    
    ###############
    # jfu
    ###############

    url(FILE + r'(?P<post_id>\d+)/upload/', f_views.upload, name = 'jfu_upload' ),
    url(FILE + r'(?P<post_id>\d+)/delete/(?P<pk>\d+)$', f_views.upload_delete, name = 'jfu_delete' ),
    url(FILE + r'/files/$', f_views.view_file_list, name = 'view_file_list' ),


    ###############
    # BOARD
    ###############

    url(BOARD + r'create/$', b_views.create_board, name='create_board'),

    url(BOARD + r'list/$', b_views.list_board, name='list_board'),
    url(BOARD + r'(?P<board_id>\d+)/create/$', b_views.create_post, name='create_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/edit/$', b_views.edit_post, name='edit_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/delete/$', b_views.delete_post, name='delete_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/$', b_views.create_comment, name='create_comment'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', b_views.delete_comment, name='delete_comment'),

    url(BOARD + r'(?P<board_id>\d+)/view/(?P<post_id>\d+)$', b_views.view_post, name='view_post'),


    ###############
    # EVENT
    ###############

    url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),

    url(EVENT + r'get/$', e_views.get_event_as_json, name='get_event'),
    #url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),
    url(EVENT + r'edit/$', e_views.edit_event, name='edit_event'),
    url(EVENT + r'delete/$', e_views.delete_event, name='delete_event'),
    url(EVENT + r'create/$', e_views.create_event, name='create_event'),

    #url(EVENT + r'finish/$', e_views.finish_event_as_json, name='finish_event'),
    #url(EVENT + r'unfinish/$', e_views.unfinish_event_as_json, name='unfinish_event'),

    url(EVENT + r'finish/(?P<event_id>\d+)/$', e_views.finish_event, name='finish_event'),
    url(EVENT + r'unfinish/(?P<event_id>\d+)/$', e_views.unfinish_event, name='unfinish_event'),


    ###############
    # CORE
    ###############

    url(r'^s/', include('core.urls', namespace='core')),

    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^account/', include('account.urls', namespace='account')),


    url(r'^chat/', include('chat.urls', namespace='chat')),

    (r'^summernote/', include('django_summernote.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

event/models.py
#-*- coding: utf-8 -*-
from django.db import models

from core.models import StudyGroup
from account.models import Student
from tag.models import Tag

class Event(models.Model):
    name = models.CharField(max_length=30)
    details = models.CharField(max_length=50, blank=True)

    start = models.DateTimeField()
    end = models.DateTimeField(blank=True, null=True)

    allDay = models.BooleanField(default=True)

    creator = models.ForeignKey(Student, related_name='event_creator')
    assigned_to = models.ManyToManyField(Student, related_name='assigned_to')
    finished_student = models.ManyToManyField(Student, related_name='finished_student')

    study_group = models.ForeignKey(StudyGroup, null=True)
    tag_set = models.ManyToManyField(Tag, blank=True, null=True)

    def __unicode__(self):
        #return "%s : %s ~ %s" % (self.name, self.start, self.end)
        return "%s" % (self.name)

    def get_start_as_korean(self):
        if self.start.hour == 12 and self.start.minute == 0:
            return "%s월 %s일" % (self.start.month,
                                  self.start.day)
        else:
            return "%s월 %s일  %s시 %s분" % (self.start.month,
                                             self.start.day,
                                             self.start.hour,
                                             self.start.minute)

    def get_end_as_korean(self):
        if self.end.hour == 12 and self.end.minute == 0:
            return "%s월 %s일" % (self.end.month,
                                  self.end.day)
        else:
            return "%s월 %s일  %s시 %s분" % (self.end.month,
                                             self.end.day,
                                             self.end.hour,
                                             self.end.minute)

    def is_all_day(self):
        return (self.start.month == self.end.month and self.start.day == self.end.day)

    def get_all_day(self):
        return "%s월 %s일" % (self.start.month, self.start.day)

event/views.py
from django.shortcuts import render, redirect, render_to_response, RequestContext, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django import http
from django.http import HttpResponse
from django.utils import timezone
import json
import datetime

import dateutil.parser
from utils.func import *

from .models import Event
from core.models import StudyGroup


########################
# Calendar
########################

@login_required
def view_calendar(request, study_group_id=None):
    #form = EventForm(data=request.POST or None, user=request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)
    template = 'event/view_calendar.html'

    return render(request, template, {'study_group': study_group, })

########################
# Event
########################

@login_required
def create_event(request, study_group_id=None):
    current_student = get_student_from_user(request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.is_ajax() and request.method == "POST":
        title = request.POST.get('title')
        start_timestamp = request.POST.get('start')
        end_timestamp = request.POST.get('end')
        allDay = request.POST.get('allDay')
        assigned_list = request.POST.get('assigned_list')

        assigned_list = assigned_list.split(',')

        if allDay is 'true':
            allDay = True
        else:
            allDay = False

        start = dateutil.parser.parse(start_timestamp)
        end = dateutil.parser.parse(end_timestamp)

        event = Event(name=title, details='', start=start, end=end, creator=current_student, study_group=study_group)
        event.save()

        for email in assigned_list:
            student = Student.objects.get(user__username=email)
            event.assigned_to.add(student)

        event.save()

        study_group.event_set.add(event)

        #movie_json = {}
        #html = t.render(Context(context))

        #movie_json['source'] = html

        #results = []
        #results.append(movie_json)

        #data = json.dumps(results)
        data = "success"
    else:
        data = "fail"

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

@login_required
def create_event_view(request):
    form = EventForm(data=request.POST or None, user=request.user)
    template = 'core/create_event.html'

    return render(request, template, {'form': form,  })

########################
# Finish event
########################

@login_required
def finish_event_as_json(request, study_group_id=None):
    current_student = get_student_from_user(request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.is_ajax() and request.method == "POST":
        id = request.POST.get('id')

        event = Event.objects.get(id=id)

        if current_student in event.finished_student.all():
            event.finished_student.add(current_student)
            data = "success"
        else:
            data = "fail: already finished"
    else:
        data = "fail"

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

@login_required
def unfinish_event_as_json(request, study_group_id=None):
    current_student = get_student_from_user(request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.is_ajax() and request.method == "POST":
        id = request.POST.get('id')

        event = Event.objects.get(id=id)

        if current_student in event.finished_student.all():
            event.finished_student.add(current_student)
            data = "success"
        else:
            data = "fail: not finished"
    else:
        data = "fail"

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

########################
# Finish event
########################

@login_required
def finish_event(request, study_group_id=None, event_id=None):
    current_student = get_student_from_user(request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    event = Event.objects.get(id=event_id)

    if current_student not in event.finished_student.all():
        event.finished_student.add(current_student)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def unfinish_event(request, study_group_id=None, event_id=None):
    current_student = get_student_from_user(request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    event = Event.objects.get(id=event_id)

    if current_student in event.finished_student.all():
        event.finished_student.remove(current_student)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


########################
# Edit event
########################

@login_required
def edit_event(request, study_group_id=None):
    current_student = get_student_from_user(request.user)
    #study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.is_ajax() and request.method == "POST":
        id = request.POST.get('id')
        dayDelta = int(request.POST.get('dayDelta'))
        minuteDelta = int(request.POST.get('minuteDelta'))

        event = Event.objects.get(id=id)

        event.start = event.start + datetime.timedelta(days=dayDelta) \
                                  + datetime.timedelta(minutes=dayDelta)
        event.end = event.end + datetime.timedelta(days=dayDelta) \
                              + datetime.timedelta(minutes=dayDelta)

        event.save()

        data = "success"
    else:
        data = "fail"

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

########################
# Complete event
########################

@login_required
def complete_event(request, study_group_id=None):
    current_student = get_student_from_user(request.user)
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.is_ajax() and request.method == "POST":
        id = request.POST.get('id')
        dayDelta = int(request.POST.get('dayDelta'))
        minuteDelta = int(request.POST.get('minuteDelta'))

        event = Event.objects.get(id=id)

        event.start = event.start + datetime.timedelta(days=dayDelta) \
                                  + datetime.timedelta(minutes=dayDelta)
        event.end = event.end + datetime.timedelta(days=dayDelta) \
                              + datetime.timedelta(minutes=dayDelta)

        event.save()

        data = "success"
    else:
        data = "fail"

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

########################
# Delete event
########################

@login_required
def delete_event(request, study_group_id=None):
    current_student = get_student_from_user(request.user)
    #study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.is_ajax() and request.method == "POST":
        id = request.POST.get('id')

        event = Event.objects.get(id=id)
        event.delete()

        data = "success"
    else:
        data = "fail"

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

########################
# Calendar
########################

@login_required
def view_calendar(request, study_group_id=None):
    #form = EventForm(data=request.POST or None, user=request.user)
    template = 'core/view_calendar.html'

    return render(request, template, {})

@login_required
def get_event_as_json(request, study_group_id=None): 
    current_student = get_student_from_user(request.user)

    if study_group_id == '0':
        events = current_student.assigned_to.all()
    else:
        study_group = StudyGroup.objects.get(unique_id=study_group_id)
        events = study_group.event_set.all()

    event_list = []

    for event in events: 
        event_start = event.start.astimezone(timezone.get_default_timezone()) 
        event_end = event.end.astimezone(timezone.get_default_timezone())

        if event_start.hour == 0 and event_start.minute == 0: 
            Allday = True 
        else: 
            Allday = False

        student_list = []
        for student in event.assigned_to.all():
            student_list.append(student.user.username)

        student_list = ','.join(student_list)

        if current_student in event.finished_student.all():
            finished = True
        else:
            finished = False

        event_list.append ({ 
            'id':  event.id , 
            'unique_id':  event.study_group.unique_id , 
            'start':  event_start.strftime ( '%Y-%m- %d %H:%M:%S' ), 
            'end':  event_end.strftime ( '%Y-%m- %d %H:%M:%S' ), 
            'title':  event.name, 
            'allDay': Allday,
            'student_list': student_list,
            'finished': finished,
        })

    if len(event_list)  ==  0 : 
        raise http.Http404 
    else : 
        return http.HttpResponse(json.dumps(event_list), content_type = 'application/json' )

templates/event/script.html
<script type="text/javascript"> 

var border_color = '#378006'

$(document).ready(function() {
  var student_list = [];
  var email_list = [];

  {% for student in study_group.student_set.all %}
    student_list.push("{{ student.get_id }}");
    email_list.push("{{ student }}");
  {% endfor %}

  var options = "";

  for (var i=0; i<student_list.length; i++) {
    options += (i+1) + " : " + student_list[i] + "  ";
  }
  
  var date = new Date();
  var d = date.getDate();
  var m = date.getMonth();
  var y = date.getFullYear();
  
  var calendar = $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      //right: 'month',//,agendaWeek',
    },

    eventColor: border_color,

    {% if user.student in study_group.student_set.all %}

    editable: true,
    selectable: true,
    selectHelper: true,

    select: function(start, end, allDay) {
      var title = prompt('Event Title:');

      $('#calendar-guide-step-1>span').removeClass('hide');

      if (title) {
        var option = prompt(options+':');

        if (option != "")
          $('#calendar-guide-step-2>span').removeClass('hide');

        var assigned_list = [];
        option = option.split(',')

        var assigned_list_as_string = "";

        for (var i=0; i<option.length; i++) {
          var num = parseInt(option[i] - 1);
          if (num > option.length || num < 0)
            continue;
          assigned_list.push(email_list[num]);
          assigned_list_as_string += student_list[num] + " ,";
        }

        if (option.length > 0)
          assigned_list_as_string = assigned_list_as_string.substr(0, assigned_list_as_string.length - 2);

        var start_date = $.fullCalendar.formatDate(start,"yyyy-MM-dd-hh-mm");
        var end_date = $.fullCalendar.formatDate(end,"yyyy-MM-dd-hh-mm");

        calendar.fullCalendar('renderEvent',
          {
            title: title + " - " + assigned_list_as_string,
            start: start,
            end: end,
            allDay: allDay,
          },
          true // make the event "stick"
        );
        jQuery.post(
          '{% url 'create_event' study_group_id=study_group.unique_id %}',
          {
            title: title,
            start: start_date,
            end: end_date,
            allDay: allDay,
            assigned_list: assigned_list.toString(),
          }
        );

        //location.href = "{% url 'core:view_study_group' study_group_id=study_group.unique_id %}";
      }
      calendar.fullCalendar('unselect');
    },
    /*eventSources: [
      {
        url: '{% url 'get_event' study_group.unique_id %}',
        type: 'POST',
        data: {
          student_list: student_list,
        },
        success: function(doc) {
          var events = [];
          x=events;
          $(doc).find('event').each(function() {
          events.push({
              title: $(this).attr('title'),
              start: $(this).attr('start') // will be parsed
            });
          });
          //callback(events);
        },
        error: function() {
          //alert('there was an error while fetching events!');
        },
        //color: 'yellow',   // a non-ajax option
        textColor: 'black' // a non-ajax option
      }
    ],*/
    eventClick: function(calEvent, jsEvent, view) {
      $(this).css('border-color', 'red');

      var title = calEvent.title.split('-')[0].trim();
      var isDelete = confirm('Are you sure to delete "' + title + '"');
      
      if (isDelete) {
        jQuery.post(
          '{% url 'delete_event' study_group_id=study_group.unique_id %}',
          {
            id: calEvent.id,
          }
        );
        $('#calendar-guide-step-4>span').removeClass('hide');

        $(this).remove()
      } else {
        $(this).css('border-color', border_color);
      }
      //alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
      //alert('View: ' + view.name);

      // change the border color just for fun
    },
    eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc) {
      if (!confirm("Are you sure about this change?")) {
        revertFunc();
      } else {
        jQuery.post(
          '{% url 'edit_event' study_group_id=study_group.unique_id %}',
          {
            id: event.id,
            dayDelta: dayDelta,
            minuteDelta: minuteDelta,
          }
        );

        $('#calendar-guide-step-3>span').removeClass('hide');
      }
    },

    {% endif %}
    events: function(start, end, callback) {
      $.ajax({
        url: '{% url 'get_event' study_group.unique_id %}',
        dataType: 'json',
        data: {
          // our hypothetical feed requires UNIX timestamps
          //start: Math.round(start.getTime() / 1000),
          //end: Math.round(end.getTime() / 1000)
        },
        success: function(data) {
          var events = [];
          $(data).each(function() {
            var student_list = $(this).attr('student_list');
            student_list = student_list.split(',')

            var student_list_as_string = '';

            for(var i=0; i<student_list.length; i++) {
              student_list[i] = student_list[i].split('@')[0];
              student_list_as_string += student_list[i] + ", ";
            }

            if (student_list.length > 0)
              student_list_as_string = student_list_as_string.substr(0, student_list_as_string.length - 2);

            if ($(this).attr('finished')) {
              events.push({
                // title: $(this).attr('title') + "\r\n" + student_list,
                id: $(this).attr('id'),
                unique_id: $(this).attr('unique_id'),
                title: $(this).attr('title') + " - " + student_list_as_string,
                start: $(this).attr('start'),
                end: $(this).attr('end'),
                allDay: $(this).attr('allDay'),
                //student_list: $(this).attr('student_list'),
                className: 'event-finished',
              });
            } else {
              events.push({
                // title: $(this).attr('title') + "\r\n" + student_list,
                id: $(this).attr('id'),
                unique_id: $(this).attr('unique_id'),
                title: $(this).attr('title') + " - " + student_list_as_string,
                start: $(this).attr('start'),
                end: $(this).attr('end'),
                allDay: $(this).attr('allDay'),
                //student_list: $(this).attr('student_list'),
              });
            }
          });
          callback(events);
        }
      });
    },
  });
  
});

</script>

templates/event/script_without_study_group.html
<script type="text/javascript"> 

var border_color = '#378006'

$(document).ready(function() {
  var options = "";

  var student_list = [];
  var email_list = [];

  for (var i=0; i<student_list.length; i++) {
    options += (i+1) + " : " + student_list[i] + "  ";
  }
  
  var date = new Date();
  var d = date.getDate();
  var m = date.getMonth();
  var y = date.getFullYear();
  
  var calendar = $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      //right: 'month',//,agendaWeek'
    },

    selectable: true,
    selectHelper: true,
    eventColor: border_color,

    //editable: true,

    eventClick: function(calEvent, jsEvent, view) {
      if (calEvent.finished) {
        $.ajax({
          url: '/s/'+calEvent.unique_id+'/event/unfinish/'+calEvent.id+'/',
          type: 'POST',
          data: { id: calEvent.id },
          success: function(data) { location.reload() },
        });
        /*jQuery.post(
          '/s/'+calEvent.unique_id+'/event/unfinish/'+calEvent.id+'/',
          {
            id: calEvent.id,
          },
          location.reload()
        );*/
      } else {
        $.ajax({
          url: '/s/'+calEvent.unique_id+'/event/finish/'+calEvent.id+'/',
          type: 'POST',
          data: { id: calEvent.id },
          success: function(data) { location.reload() },
        });
        /*jQuery.post(
          '/s/'+calEvent.unique_id+'/event/finish/'+calEvent.id+'/',
          {
            id: calEvent.id,
          },
          location.reload()
        );*/
      }
    },
    events: function(start, end, callback) {
      $.ajax({
        url: '{% url 'get_event' study_group_id='0' %}',
        dataType: 'json',
        data: {
          // our hypothetical feed requires UNIX timestamps
          //start: Math.round(start.getTime() / 1000),
          //end: Math.round(end.getTime() / 1000)
        },
        success: function(data) {
          var events = [];
          $(data).each(function() {
            var student_list = $(this).attr('student_list');
            student_list = student_list.split(',')

            var student_list_as_string = '';

            for(var i=0; i<student_list.length; i++) {
              student_list[i] = student_list[i].split('@')[0];
              student_list_as_string += student_list[i] + ", ";
            }

            if (student_list.length > 0)
              student_list_as_string = student_list_as_string.substr(0, student_list_as_string.length - 2);

            if ($(this).attr('finished')) {
              events.push({
                // title: $(this).attr('title') + "\r\n" + student_list,
                id: $(this).attr('id'),
                unique_id: $(this).attr('unique_id'),
                title: $(this).attr('title') + " - " + student_list_as_string,
                start: $(this).attr('start'),
                end: $(this).attr('end'),
                allDay: $(this).attr('allDay'),
                //student_list: $(this).attr('student_list'),
                className: 'event-finished',
                finished: true,
              });
            } else {
              events.push({
                // title: $(this).attr('title') + "\r\n" + student_list,
                id: $(this).attr('id'),
                unique_id: $(this).attr('unique_id'),
                title: $(this).attr('title') + " - " + student_list_as_string,
                start: $(this).attr('start'),
                end: $(this).attr('end'),
                allDay: $(this).attr('allDay'),
                //student_list: $(this).attr('student_list'),
                finished: false,
              });
            }
          });
          callback(events);
        }
      });
    },
  });
  
});

</script>

templates/event/view_calendar.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}
  {% if not total_calendar %}
    {% include 'event/script.html' %}
  {% else %}
    {% include 'event/script_without_study_group.html' %}
  {% endif %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}

        {% if not total_calendar %}
          {% include "sub_navbar.html" %}
        {% endif %}

        <div class="col-sm-fset-6 col-md-8 col-md-offset-4 main">
          <!--<h1 class="page-header">{{ study_group.name }}</h1>
          <p>{{ study_group.details }}</p>-->

          <div id='calendar'></div>

          {% if user.student.display_calendar_guide %}
            <script type="text/javascript">

function confirm_display_calendar_guide() {
  if(confirm('Are you sure to stop displaying calendar guide?')) {
    location.href="{% url 'core:no_calendar_guide' %}";
  }
}

            </script>

            <br />
            <ul class="list-group">
              <li class="list-group-item active">
                <button class="btn btn-sm btn-warning pull-right" onclick="confirm_display_calendar_guide();"><span class="glyphicon glyphicon-remove"></span> 영원히 보지않기</button>
                <b style="color: white; serif; font-size:22px;">캘린더 가이드</b>
              </li>
              <li class="list-group-item" id="calendar-guide-step-1">1. 빈공간 드래그 or 클릭 : 새 이벤트 만들기<span class="glyphicon glyphicon-ok pull-right hide"></span></li>
              <li class="list-group-item" id="calendar-guide-step-2">2. 번호 입력 : 이벤트 멤버에게 할당하기<span class="glyphicon glyphicon-ok pull-right hide"></span</li>
              <li class="list-group-item" id="calendar-guide-step-3">3. 이벤트 드래그 : 날짜 변경하기<span class="glyphicon glyphicon-ok pull-right hide"></span</li>
              <li class="list-group-item" id="calendar-guide-step-4">4. 이벤트 클릭 : 이벤트 삭제하기<span class="glyphicon glyphicon-ok pull-right hide"></span</li>
            </ul>
          {% endif %}


        </div>
      </div>
    </div>

{% endblock %}

templates/event/view_calendar_without_subnav.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}
  {% if not total_calendar %}
    {% include 'event/script.html' %}
  {% else %}
    {% include 'event/script_without_study_group.html' %}
  {% endif %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}

        {% if not total_calendar %}
          {% include "sub_navbar.html" %}
        {% endif %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!--<h1 class="page-header">{{ study_group.name }}</h1>
          <p>{{ study_group.details }}</p>-->

          <div id='calendar'></div>
        </div>
      </div>
    </div>

{% endblock %}