account/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^follow/$', 'account.views.follow', name='follow'),

    url(r'^profile/$', 'account.views.view_profile', name='view_profile'),
    url(r'^sign_in/$', 'account.views.sign_in', name='sign_in'),
    url(r'^sign_up/$', 'account.views.sign_up', name='sign_up'),
    url(r'^sign_out/$', 'account.views.sign_out', name='sign_out'),
)

chat/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'chat.views.home', name='home'),
    url(r'^node_api$', 'chat.views.node_api', name='node_api'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

core/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='home'),

    url(r'^calendar/$', views.view_calendar, name='view_calendar'),
    url(r'^no-calendar-guide/$', views.no_calendar_guide, name='no_calendar_guide'),

    url(r'^search/tag/', views.search_study_group_with_tag, name='search_study_group_with_tag'),
    url(r'^search/', views.search_study_group, name='search_study_group'),
    url(r'^help/$', views.view_help, name='view_help'),

    url(r'^create/$', views.create_study_group, name='create_study_group'),
    url(r'^(?P<study_group_id>\w+)/delete/$', views.delete_study_group, name='delete_study_group'),
    url(r'^join/$', views.join_study_group, name='join_study_group'),
    url(r'^like/$', views.like_study_group, name='like_study_group'),

    url(r'^(?P<study_group_id>\w+)/$', views.view_study_group, name='view_study_group'),

    url(r'^group/board/edit/$', include('django_summernote.urls')),

    url(r'^articles/comments/', include('django.contrib.comments.urls')),
)

studyplan/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from core import views as c_views
from board import views as b_views
from event import views as e_views
from file import views as f_views

STUDY = r'^s/(?P<study_group_id>\w+)/'

BOARD = STUDY + r'board/'
EVENT = STUDY + r'event/'
FILE = STUDY + r'file/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'core.views.index'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    #(r'^asset/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.ASSET_ROOT}),

    
    ###############
    # jfu
    ###############

    url(FILE + r'(?P<post_id>\d+)/upload/', f_views.upload, name = 'jfu_upload' ),
    url(FILE + r'(?P<post_id>\d+)/delete/(?P<pk>\d+)$', f_views.upload_delete, name = 'jfu_delete' ),
    url(FILE + r'/files/$', f_views.view_file_list, name = 'view_file_list' ),


    ###############
    # BOARD
    ###############

    url(BOARD + r'create/$', b_views.create_board, name='create_board'),

    url(BOARD + r'list/$', b_views.list_board, name='list_board'),
    url(BOARD + r'(?P<board_id>\d+)/create/$', b_views.create_post, name='create_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/edit/$', b_views.edit_post, name='edit_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/delete/$', b_views.delete_post, name='delete_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/$', b_views.create_comment, name='create_comment'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', b_views.delete_comment, name='delete_comment'),

    url(BOARD + r'(?P<board_id>\d+)/view/(?P<post_id>\d+)$', b_views.view_post, name='view_post'),


    ###############
    # EVENT
    ###############

    url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),

    url(EVENT + r'get/$', e_views.get_event_as_json, name='get_event'),
    #url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),
    url(EVENT + r'edit/$', e_views.edit_event, name='edit_event'),
    url(EVENT + r'delete/$', e_views.delete_event, name='delete_event'),
    url(EVENT + r'create/$', e_views.create_event, name='create_event'),

    #url(EVENT + r'finish/$', e_views.finish_event_as_json, name='finish_event'),
    #url(EVENT + r'unfinish/$', e_views.unfinish_event_as_json, name='unfinish_event'),

    url(EVENT + r'finish/(?P<event_id>\d+)/$', e_views.finish_event, name='finish_event'),
    url(EVENT + r'unfinish/(?P<event_id>\d+)/$', e_views.unfinish_event, name='unfinish_event'),


    ###############
    # CORE
    ###############

    url(r'^s/', include('core.urls', namespace='core')),

    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^account/', include('account.urls', namespace='account')),


    url(r'^chat/', include('chat.urls', namespace='chat')),

    (r'^summernote/', include('django_summernote.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

board/models.py
from django.db import models

from core.models import Student
from tag.models import Tag

# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=200)
    details = models.CharField(max_length=300)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Post(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField(blank=False)

    tag_set = models.ManyToManyField(Tag, blank=True, null=True)
    board = models.ForeignKey(Board, blank=True, null=True)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    viewed_student = models.ManyToManyField(Student, blank=True, null=True, related_name='viewed_student')

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    content = models.TextField(blank=False)

    post = models.ForeignKey(Post, blank=True, null=True)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.content

core/models.py
#-*- coding: utf-8 -*-
import uuid
import base64

from django.db import models
from django.utils.encoding import smart_unicode

from account.models import Student
from board.models import Board
from tag.models import Tag

# Create your models here.
class StudyGroup(models.Model):
    name = models.CharField(max_length=200)
    details = models.CharField(max_length=300)

    student_set = models.ManyToManyField(Student, blank=True, null=True, related_name='study_group_set')
    liked_student_set = models.ManyToManyField(Student, blank=True, null=True, related_name='liked_student_set')

    tag_set = models.ManyToManyField(Tag, blank=True, null=True)
    board_set = models.ManyToManyField(Board, null=True)

    creator = models.ForeignKey(Student, related_name='study_group_creator')
    leader = models.ManyToManyField(Student, related_name='leader')
    liked_student_set = models.ManyToManyField(Student, null=True, related_name='liked_student_set')

    is_private = models.BooleanField(default=False)

    unique_id = models.CharField(max_length=100, null=True, blank=True, unique=True)

    #def __init__(self, *args, **kwargs):
    #    super(StudyGroup, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.unique_id:
            while True:
                unique_id = base64.b64encode(str(uuid.uuid4()))[:10]
                group = StudyGroup.objects.filter(unique_id=unique_id)

                if len(group) is 0:
                    self.unique_id = unique_id
                    break
            
        super(StudyGroup, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

core/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, render_to_response, RequestContext, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django import http
import json, random

from .forms import StudyGroupForm, EventForm
from account.forms import StudentCreateForm
from account.models import Student
from core.models import StudyGroup
from board.models import Post
from board.forms import CommentForm

from utils.func import *
from utils.say import *

########################
# Index
########################

def index(request, auth_form=None, user_form=None):
    form = StudentCreateForm(request.POST or None)
    context = RequestContext(request)

    if request.user.is_authenticated():
        current_student = get_student_from_user(request.user)

        if current_student is None:
            logout(request)
            redirect('/')
        else:
            print current_student

        # Study group for current User
        #study_group_list = current_student.study_group_set.all()

        study_group_list = StudyGroup.objects.all()
        student_list = Student.objects.all()

        total_event_count = 0.0
        finished_event_count = 0.0

        for event in current_student.assigned_to.all():
            total_event_count += 1

            if current_student in event.finished_student.all():
                finished_event_count += 1

        try:
            event_finished_percent = finished_event_count / total_event_count * 100.0
        except:
            event_finished_percent = -1

        for student in student_list:
            if student in current_student.friends.all():
                student.isFriend = True
            else:
                student.isFriend = False

        return render(request,
                      'core/home.html',
                      {'auth_form': auth_form,
                       'user_form': user_form,
                       'total_event_count': total_event_count,
                       'finished_event_count': finished_event_count,
                       'event_finished_percent' : event_finished_percent,
                       'student_list': student_list,
                       'study_group_list' : study_group_list})

    return render_to_response('core/index.html', locals(), context_instance=context)

########################
# Calendar
########################

@login_required
def view_calendar(request, study_group_id=None):
    #form = EventForm(data=request.POST or None, user=request.user)
    template = 'event/view_calendar_without_subnav.html'

    return render(request, template, {'total_calendar': True})

########################
# View help
########################

@login_required
def view_help(request):
    #form = EventForm(data=request.POST or None, user=request.user)
    template = 'core/view_help.html'

    post = Post.objects.get(id=1)
    form = CommentForm(data=request.POST or None, user=request.user, post_id=1)

    return render(request, template, {'post': post, 'form': form})


########################
# Search group
########################

@login_required
def search_study_group(request): #, search_query=""):
    #form = EventForm(data=request.POST or None, user=request.user)
    template = 'core/search_study_group.html'
    search_query = request.GET.get('search_query', '')

    study_group_list = StudyGroup.objects.filter(name__contains=search_query)

    s = random.choice(say.keys())

    return render(request,
                  template,
                  {'study_group_list' : study_group_list,
                   'say': say[s] + " : " + s,
                   'search_query': search_query })

########################
# Search group with tag
########################

@login_required
def search_study_group_with_tag(request): #, search_query=""):
    #form = EventForm(data=request.POST or None, user=request.user)
    template = 'core/search_study_group.html'
    search_tag = request.GET.get('search_tag', '')

    study_group_list = StudyGroup.objects.filter(tag_set__name__contains=search_tag)

    s = random.choice(say.keys())

    return render(request,
                  template,
                  {'study_group_list' : study_group_list,
                   'say': say[s] + " : " + s,
                   'search_tag': search_tag })

########################
# Do not display calendar guide
########################

@login_required
def no_calendar_guide(request):
    current_student = get_student_from_user(request.user) 

    current_student.display_calendar_guide = not current_student.display_calendar_guide
    current_student.save()
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


########################
# Join study group
########################

@login_required
def join_study_group(request):
    if request.method == 'POST':
        group_unique_id = request.POST.get("group_unique_id", "")
        group = StudyGroup.objects.get(unique_id=group_unique_id)

        current_student = get_student_from_user(request.user) 

        if group in current_student.study_group_set.all():
          current_student.study_group_set.remove(group)
        else:
          current_student.study_group_set.add(group)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

########################
# Like study group
########################

@login_required
def like_study_group(request):
    if request.method == 'POST':
        group_unique_id = request.POST.get("group_unique_id", "")
        group = StudyGroup.objects.get(unique_id=group_unique_id)

        current_student = get_student_from_user(request.user) 

        if current_student in group.liked_student_set.all():
          group.liked_student_set.remove(current_student)
        else:
          group.liked_student_set.add(current_student)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

########################
# View study group
########################

@login_required
def view_study_group(request, study_group_id=None):
    study_group = StudyGroup.objects.get(unique_id=study_group_id)
    template = 'event/view_calendar.html'

    return render(request, template, {'study_group': study_group,  })

########################
# Create Study Group
########################

@login_required
def create_study_group(request):
    form = StudyGroupForm(data=request.POST, user=request.user)
    context = RequestContext(request)
    template = 'core/create_study_group.html'

    if request.method == "POST":
        if form.is_valid():
            group = form.save(commit=False)
            group.save()

            return redirect('/')
        else:
            return create_study_group_view(request)

    return create_study_group_view(request)

########################
# Delete Study Group
########################

@login_required
def delete_study_group(request, study_group_id=None):
    group = StudyGroup.objects.get(unique_id=study_group_id)
    group.delete()

    return redirect('/')

@login_required
def create_study_group_view(request):
    form = StudyGroupForm(data=request.POST or None, user=request.user)
    template = 'core/create_study_group.html'

    return render(request, template, {'form': form,  })

# Create your views here.
"""
class CreateStudyGroup(JSONResponseMixin, LoginRequiredMixin, CreateView):
    template_name = None  # JavaScript-only view
    model = Group
    form_class = StudyGroupForm

    def get(self, request, *args, **kwargs):
        if not request.is_ajax():
            return HttpResponseRedirect(reverse('core:recent-pins'))
        return super(CreateImage, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        image = form.save()

        return self.render_json_response({
            'success': {
                'id': StudyGroup.id
            }
        })

    def form_invalid(self, form):
        return self.render_json_response({'error': form.errors})
"""

templates/core/create_event.html
{% extends 'base.html' %}

{% block title %}Create Event{% endblock %}

{% block active_create_event %}active{% endblock %}

{% block content_with_nav %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <form class="form-signin" role="form" action="{% url 'core:create_event' %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <button class="btn btn-lg btn-success btn-block" type="submit">Create Group</button>
          </form>
        </div>
      </div>
    </div>

{% endblock %}

templates/core/create_study_group.html
{% extends 'base.html' %}

{% block title %}Create study group{% endblock %}

{% block create_study_group %}active{% endblock %}

{% block content_with_nav %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <form class="form-signin" role="form" action="{% url 'core:create_study_group' %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <button class="btn btn-lg btn-success btn-block" type="submit">Create Group</button>
          </form>
        </div>
      </div>
    </div>

{% endblock %}

templates/core/help.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}
  <script type="text/javascript">
    function confirm_delete_comment(comment_id) {
      var conf= confirm('Are you sure to delete this comment');
      if (conf) {
        location.href='/s/0/board/0/{{ post.id }}/comment/' + comment_id + '/delete/';
      }
    }
  </script>



  <div class="col-xs-10 col-xs-offset-2">

    <div class="text-center">
      <h1 style="font-family: 'Hanna', serif; font-size: 50px;">피드백 환영 :)</h1>
    </div>

    <div class="col-xs-10 container-fluid">
      <div class="row">
        {% include "navbar.html" %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!--<h1 class="page-header">Welcome {{ user.username }}!</h1>-->

            {% for comment in post.comment_set.all %}
            <div class="well">
              {% if comment.creator.user == user %}
                <div class="pull-right">
                  <button type="button" class="btn btn-warning btn-sm" onclick="confirm_delete_comment({{ comment.id }})"/>Delete</button>
                </div>
              {% endif %}
              <div class="pull-left">
                <img class="img-responsive img-thumbnail comment-thumbnail" src="{{ comment.creator.gravatar_middle_url }}">
              </div>
              <div class="comment-content">
                <div class="comment-author">
                  <span class="name"><a href=#" rel="external nofollow" class="url">{{ comment.creator }}</a></span>
                  <small>{{ comment.created_at }}</small>
                </div>

                <div class="comment-text">
                  {{ comment.content | safe }}
                </div>
              </div>
           </div>
           {% endfor %}

          <form class="form-comment" role="form" action="{% url 'create_comment' study_group_id='0' board_id='0' post_id=post.id %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <button class="btn btn-sm btn-success btn-block" style="margin-bottom: 30px;" type="submit">Write comment</button>
          </form>
        </div>
      </div>
    </div>

  </div>

{% endblock %}

templates/core/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!--<h1 class="page-header">Welcome {{ user.username }}!</h1>-->

          {% include 'core/list_group_event.html' with student=user.student %}

          <div class="list-group">
            <div class="list-group-item active">
              <h4 class="list-group-item-heading">
                Study Group list
              </h4>
            </div>
            {% for group in study_group_list %}
              {% include 'core/list_group_item_study_group.html' %}
            {% endfor %}
          </div>

          <div class="list-group">
            <div class="list-group-item active">
              <h4 class="list-group-item-heading">
                User list
              </h4>
            </div>
            {% for student in student_list %}
              <div class="list-group-item">
                <form role="form" action="{% url 'account:follow' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" value="{{ student }}" name="username">
                    {% if student.isFriend %}
                  <button type="submit" class="student-follow-btn btn btn-success btn-lg pull-right">
                      <span class="glyphicon glyphicon-star"></span> Friend
                    {% else %}
                  <button type="submit" class="student-follow-btn btn btn-primary btn-lg pull-right">
                      <span class="glyphicon glyphicon-star-empty"></span> Follow
                    {% endif %}
                  </button>
                </form>

                <h4 class="list-group-item-heading">
                  <a href="{% url 'account:view_profile' %}?user_id={{ student.user.username }}"> {{ student }} </a>
                </h4>
                <p class="list-group-item-text">
                  {{ student.school }} | 

                  {% for study_group in student.studygroup_set.all %}
                    {% if not study_group.is_private %}
                      <a href="{% url 'core:view_study_group' study_group.unique_id %}">{{ study_group }}</a>, 
                    {% endif %}
                  {% endfor %}
                </p>

                <!--<span class="glyphicon glyphicon-chevron-right"></span>
                <span class="badge">{{ group.student_set.all | length }}</span>-->
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/core/list_group_event.html
<div class="list-group">
  <div class="list-group-item active">
    <h4 class="list-group-item-heading">
      To-do
    </h4>
  </div>
  <div class="list-group-item">
    <div class="text-center">
      {% if student.assigned_to.count == 0 %}
        <p>할일이 없으시네요 :)</p>
      {% elif event_finished_percent == -1 %}
        <p>할일이 없어요 :|</p>
      {% elif event_finished_percent != 100 %}
        <p>아직 할일이 남았어요 :(</p>
      {% else %}
        <p>할일을 모두 끝내셨군요 :^)</p>
      {% endif %}
    </div>
    <div class="progress">
      {% if event_finished_percent != 100 %}
        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{ finished_event_count }}" aria-valuemin="0" aria-valuemax="{{ total_event_count }}" style="width: {{ event_finished_percent }}%;">
      {% else %}
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{ finished_event_count }}" aria-valuemin="0" aria-valuemax="{{ total_event_count }}" style="width: {{ event_finished_percent }}%;">
      {% endif %}
        <span class="sr-only">60% Complete</span>
      </div>
    </div>
  </div>
  {% for event in student.assigned_to.all %}
    <div class="list-group-item">
      {% if student in event.finished_student.all %}
        <button type="button" class="btn btn-success btn-lg pull-right" onclick="location.href='{% url 'unfinish_event' study_group_id=event.study_group.unique_id event_id=event.id %}'">
          <span class="glyphicon glyphicon-ok"></span> Done
        </button>
      {% else %}
        <button type="button" class="btn btn-primary btn-lg pull-right" onclick="location.href='{% url 'finish_event' study_group_id=event.study_group.unique_id event_id=event.id %}'">
          Finished?
        </button>
      {% endif %}
      <h4 class="list-group-item-heading">
        <a href="{% url 'core:view_study_group' event.study_group.unique_id %}"> {{ event.name }} </a>
      </h4>
      <p class="list-group-item-text">
        {% if event.is_all_day %}
          {{ event.get_all_day }} |
        {% else %}
          {{ event.get_start_as_korean }} ~ {{ event.get_end_as_korean }} |
        {% endif %}
        <a href="{% url 'core:view_study_group' event.study_group.unique_id %}">{{ event.study_group }}</a>
    </div>
  {% endfor %}
</div>

templates/core/list_group_item_study_group.html
{% if group.is_private and user.student not in group.student_set.all %}

{% else %}
  {% if group.is_private %}
    <div class="list-group-item list-group-item-private">
  {% else%}
    <div class="list-group-item">
  {% endif %}
    <form role="form" action="{% url 'core:like_study_group' %}" method="post">
      {% csrf_token %}
      <input type="hidden" value="{{ group.unique_id}}" name="group_unique_id">
      {% if user.student in group.liked_student_set.all %}
        <button type="submit" class="btn btn-info btn-lg pull-right">
          <span class="glyphicon glyphicon-heart"></span> Liked
          <span class="badge">{{ group.liked_student_set.count }}</span>
      {% else %}
        <button type="submit" class="btn btn-primary btn-lg pull-right">
          <span class="glyphicon glyphicon-heart"></span> Like?
          <span class="badge">{{ group.liked_student_set.count }}</span>
      {% endif %}
      </button>
    </form>

    <form role="form" action="{% url 'core:join_study_group' %}" method="post">
      {% csrf_token %}
      <input type="hidden" value="{{ group.unique_id}}" name="group_unique_id">
      {% if user.student in group.student_set.all %}
        <button type="submit" class="group-join-btn btn btn-success btn-lg pull-right" style="margin-right: 10px;">
          Joined
      {% else %}
        <button type="submit" class="group-join-btn btn btn-primary btn-lg pull-right" style="margin-right: 10px;">
          Join
      {% endif %}
      </button>
    </form>

    <h4 class="list-group-item-heading">
      <a href="{% url 'core:view_study_group' group.unique_id %}">
        {% if group.is_private and user.student in group.student_set.all %}
          <span class="glyphicon glyphicon-eye-close"></span>
        {% else %}
          <span class="glyphicon glyphicon-eye-open"></span>
        {% endif %}
        {{ group.name }}
      </a>
    </h4>
    <p class="list-group-item-text">
      {{ group.details }} | 그룹장 :
      <a href="{% url 'account:view_profile' %}?user_id={{ group.creator.user.username }}">
        {% if group.creator == user.student %}
          <span class="badge badge-me">{{ group.creator.get_id }}</span>
        {% elif group.creator in user.student.friends.all %}
          <span class="badge badge-friend">{{ group.creator.get_id }}</span>
        {% else %}
          <span class="badge">{{ group.creator.get_id }}</span>
        {% endif %}
      </a>
      {% if group.tag_set.all.count > 0 %}
        | 태그 :
        {% for tag in group.tag_set.all %}
          <a href="{% url 'core:search_study_group_with_tag' %}?search_tag={{ tag }}"<span class="badge">{{ tag }}</span></a>,
        {% endfor %}
      {% endif %}
    </p>
    <!--<span class="glyphicon glyphicon-chevron-right"></span>
    <span class="badge">{{ group.student_set.all | length }}</span>-->
  </div>
{% endif %}

templates/core/view_help.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}
  <script type="text/javascript">
    function confirm_delete_comment(comment_id) {
      var conf= confirm('Are you sure to delete this comment');
      if (conf) {
        location.href='/s/0/board/0/{{ post.id }}/comment/' + comment_id + '/delete/';
      }
    }
  </script>



  <div class="col-xs-10 col-xs-offset-2">

    <div class="text-center">
      <h1 style="font-family: 'Hanna', serif; font-size: 50px;">피드백 환영 :)</h1>
    </div>

    <div class="col-xs-10 container-fluid">
      <div class="row">
        {% include "navbar.html" %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!--<h1 class="page-header">Welcome {{ user.username }}!</h1>-->

            {% for comment in post.comment_set.all %}
            <div class="well">
              {% if comment.creator.user == user %}
                <div class="pull-right">
                  <button type="button" class="btn btn-warning btn-sm" onclick="confirm_delete_comment({{ comment.id }})"/>Delete</button>
                </div>
              {% endif %}
              <div class="pull-left">
                <img class="img-responsive img-thumbnail comment-thumbnail" src="{{ comment.creator.gravatar_middle_url }}">
              </div>
              <div class="comment-content">
                <div class="comment-author">
                  <span class="name"><a href=#" rel="external nofollow" class="url">{{ comment.creator }}</a></span>
                  <small>{{ comment.created_at }}</small>
                </div>

                <div class="comment-text">
                  {{ comment.content | safe }}
                </div>
              </div>
           </div>
           {% endfor %}

          <form class="form-comment" role="form" action="{% url 'create_comment' study_group_id='0' board_id='0' post_id=post.id %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <button class="btn btn-sm btn-success btn-block" style="margin-bottom: 30px;" type="submit">Write comment</button>
          </form>
        </div>
      </div>
    </div>

  </div>

{% endblock %}