account/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^follow/$', 'account.views.follow', name='follow'),

    url(r'^profile/$', 'account.views.view_profile', name='view_profile'),
    url(r'^sign_in/$', 'account.views.sign_in', name='sign_in'),
    url(r'^sign_up/$', 'account.views.sign_up', name='sign_up'),
    url(r'^sign_out/$', 'account.views.sign_out', name='sign_out'),
)

chat/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'chat.views.home', name='home'),
    url(r'^node_api$', 'chat.views.node_api', name='node_api'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

core/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='home'),

    url(r'^calendar/$', views.view_calendar, name='view_calendar'),
    url(r'^no-calendar-guide/$', views.no_calendar_guide, name='no_calendar_guide'),

    url(r'^search/tag/', views.search_study_group_with_tag, name='search_study_group_with_tag'),
    url(r'^search/', views.search_study_group, name='search_study_group'),
    url(r'^help/$', views.view_help, name='view_help'),

    url(r'^create/$', views.create_study_group, name='create_study_group'),
    url(r'^(?P<study_group_id>\w+)/delete/$', views.delete_study_group, name='delete_study_group'),
    url(r'^join/$', views.join_study_group, name='join_study_group'),
    url(r'^like/$', views.like_study_group, name='like_study_group'),

    url(r'^(?P<study_group_id>\w+)/$', views.view_study_group, name='view_study_group'),

    url(r'^group/board/edit/$', include('django_summernote.urls')),

    url(r'^articles/comments/', include('django.contrib.comments.urls')),
)

school/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^sign_in/', 'account.views.sign_in', name='sign_in'),
)

studyplan/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from core import views as c_views
from board import views as b_views
from event import views as e_views
from file import views as f_views

STUDY = r'^s/(?P<study_group_id>\w+)/'

BOARD = STUDY + r'board/'
EVENT = STUDY + r'event/'
FILE = STUDY + r'file/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'core.views.index'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    #(r'^asset/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.ASSET_ROOT}),

    
    ###############
    # jfu
    ###############

    url(FILE + r'(?P<post_id>\d+)/upload/', f_views.upload, name = 'jfu_upload' ),
    url(FILE + r'(?P<post_id>\d+)/delete/(?P<pk>\d+)$', f_views.upload_delete, name = 'jfu_delete' ),
    url(FILE + r'/files/$', f_views.view_file_list, name = 'view_file_list' ),


    ###############
    # BOARD
    ###############

    url(BOARD + r'create/$', b_views.create_board, name='create_board'),

    url(BOARD + r'list/$', b_views.list_board, name='list_board'),
    url(BOARD + r'(?P<board_id>\d+)/create/$', b_views.create_post, name='create_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/edit/$', b_views.edit_post, name='edit_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/delete/$', b_views.delete_post, name='delete_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/$', b_views.create_comment, name='create_comment'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', b_views.delete_comment, name='delete_comment'),

    url(BOARD + r'(?P<board_id>\d+)/view/(?P<post_id>\d+)$', b_views.view_post, name='view_post'),


    ###############
    # EVENT
    ###############

    url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),

    url(EVENT + r'get/$', e_views.get_event_as_json, name='get_event'),
    #url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),
    url(EVENT + r'edit/$', e_views.edit_event, name='edit_event'),
    url(EVENT + r'delete/$', e_views.delete_event, name='delete_event'),
    url(EVENT + r'create/$', e_views.create_event, name='create_event'),

    #url(EVENT + r'finish/$', e_views.finish_event_as_json, name='finish_event'),
    #url(EVENT + r'unfinish/$', e_views.unfinish_event_as_json, name='unfinish_event'),

    url(EVENT + r'finish/(?P<event_id>\d+)/$', e_views.finish_event, name='finish_event'),
    url(EVENT + r'unfinish/(?P<event_id>\d+)/$', e_views.unfinish_event, name='unfinish_event'),


    ###############
    # CORE
    ###############

    url(r'^s/', include('core.urls', namespace='core')),

    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^account/', include('account.urls', namespace='account')),


    url(r'^chat/', include('chat.urls', namespace='chat')),

    (r'^summernote/', include('django_summernote.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

board/models.py
from django.db import models

from core.models import Student
from tag.models import Tag

# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=200)
    details = models.CharField(max_length=300)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Post(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField(blank=False)

    tag_set = models.ManyToManyField(Tag, blank=True, null=True)
    board = models.ForeignKey(Board, blank=True, null=True)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    viewed_student = models.ManyToManyField(Student, blank=True, null=True, related_name='viewed_student')

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    content = models.TextField(blank=False)

    post = models.ForeignKey(Post, blank=True, null=True)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.content

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}


<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>다다</title>
    <meta name="title" content="다다" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="http://3.bp.blogspot.com/-KBXXyz6h6RQ/U0n3gCOx3TI/AAAAAAAACnw/i_p6HkU9uRw/s1600/gyutae.png"/>
    <!--<meta property="og:image" content="http://gyutae.herokuapp.com/media/media/gyutae.png" />-->
    <meta property="og:url" content="http://gyutae.herokuapp.com/" />
    <meta property="og:site_name" content="다다" />
    <meta property="og:description" content="다다- 당신의 스터디, 안녕하신가요?" />
    <meta property="fb:app_id" content="1441103269468905" />
    <meta name="description" content="다다">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="keywords" content="유니스트 다다, unist, 다다" />

    <!--
    start : 2014-03-28 10:46 am
                                   _           ____   ___
      ___ __ _ _ __ _ __   ___  __| |_ __ ___ |___ \ / _ \
     / __/ _` | '__| '_ \ / _ \/ _` | '_ ` _ \  __) | | | |
    | (__ (_| | |  | |_) |  __/ (_| | | | | | |/ __/| |_| |
     \___\__,_|_|  | .__/ \___|\__,_|_| |_| |_|_____|\___/
                   |_|

    end  : 2014-??-??
    -->

    <link href="/favicon.ico?1" rel="shortcut icon" type="image/vnd.microsoft.icon" />
    <link rel="image_src" type="image/jpeg" href="http://3.bp.blogspot.com/-KBXXyz6h6RQ/U0n3gCOx3TI/AAAAAAAACnw/i_p6HkU9uRw/s1600/gyutae.png" />
    <link rel="apple-touch-icon" href="http://3.bp.blogspot.com/-KBXXyz6h6RQ/U0n3gCOx3TI/AAAAAAAACnw/i_p6HkU9uRw/s1600/gyutae.png" />


    <link rel="stylesheet" href="http://fonts.googleapis.com/earlyaccess/nanumgothic.css" type="text/css" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/earlyaccess/hanna.css" type="text/css" />

    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <!--<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />-->
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap-theme.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />

    <!--<link rel="stylesheet" href="{% static 'css/metro-bootstrap.css' %}">-->

    <link href="{% static 'css/fullcalendar.css' %}" rel="stylesheet" />
    <link href="{% static 'css/fullcalendar.print.css' %}" rel="stylesheet" />

    <link href="{% static 'css/custom.less' %}" rel="stylesheet/less" type="text/css" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="{% static 'js/jquery-ui.custom.min.js' %}"></script>
    <!--<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.7.0/less.min.js"></script>

    <!--<script src="{% static 'js/metro.min.js' %}"></script>
    <script src="{% static 'js/metro-dropdown.js' %}"></script>-->

    <script src="{% static 'js/fullcalendar.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.fileupload.js' %}" type="text/javascript"></script>

    <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ko_KR/all.js#xfbml=1&appId=641444019231608";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <img alt="Gyutae logo" class="img-responsive" href="http://3.bp.blogspot.com/-KBXXyz6h6RQ/U0n3gCOx3TI/AAAAAAAACnw/i_p6HkU9uRw/s1600/gyutae.png" style="display:none;"/>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid col-sm-10 col-sm-offset-1">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="font-family: 'Hanna', serif; font-size: 27px;" href="/">다다</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="{% block profile %}{% endblock %}"><a href="{% url 'account:view_profile' %}?user_id={{ user.username }}">{{ user.username }}</a></li>
              <li class="{% block active_sign_out %}{% endblock %}"><a href="{% url 'account:sign_out' %}">Sign out</a></li>
            {% else %}
              <li class="{% block active_sign_in %}{% endblock %}"><a href="{% url 'account:sign_in' %}">Sign in</a></li>
            {% endif %}
            <li><a href="{% url 'core:view_help' %}">Help</a></li>
          </ul>
          <form id="study_group_serach_form" class="navbar-form navbar-left" action="{% url 'core:search_study_group' %}" method="GET">
            <input type="text" id="search_query" name="search_query" class="form-control" placeholder="스터디 검색...">
            <button type="submit" class="btn btn-default">검색</button>
          </form>
        </div>
      </div>
    </div>

  {% if user.is_authenticated %}
  	{% block content_with_nav %}
	  {% endblock %}
  {% else %}
    {% block jumbotron %} {% endblock %}
    <div class="container">
      <div class="row">
        {% block below_jumbotron %} {% endblock %}
      </div>
    </div>
    <div class="footer">
      <div class="container">
        <div class="text-center">
          {% block footer %} {% endblock %}
        </div>
      </div>
    </div>
  {% endif %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>-->
  </body>
</html>

templates/content_with_jumbotron.html
{% extends 'base.html' %}

{% block active_sign_in%}
	{% block inner_active_sign_in %}{% endblock %}
{% endblock %}

{% block content %}
    <div class="jumbotron">
      <div class="container">
        {% block jumbotron %} {% endblock %}
      </div>
    </div>
    <div class="container">
      <div class="row">
        {% block below_jumbotron %} {% endblock %}
      </div>
    </div>
	<div class="footer">
	  <div class="container">
		<div class="text-center">
	      {% block footer %} {% endblock %}
		</div>
	  </div>
    </div>
{% endblock %}

templates/content_with_nav.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Study</a></li>
            <li class=""><a href="#">Calendar</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li class=""><a href="#">Calendar</a></li>
            <li class=""><a href="#">Calendar</a></li>
            <li class=""><a href="#">Calendar</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>
        </div>
      </div>
    </div>
{% endblock %}

templates/content_without_nav.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Study</a></li>
            <li class=""><a href="#">Calendar</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li class=""><a href="#">Calendar</a></li>
            <li class=""><a href="#">Calendar</a></li>
            <li class=""><a href="#">Calendar</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>
        </div>
      </div>
    </div>
{% endblock %}

templates/msg.html
<!DOCTYPE html>
<html>
<head>
  <title>Realtime Django</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>
  <script src="http://localhost:4000/socket.io/socket.io.js"></script>
  <script>
    $(document).ready(function(){
      var socket = io.connect('localhost', {port: 4000});
      
      socket.on('connect', function(){
        console.log("connect");
      });
      
      var entry_el = $('#comment');
               
      socket.on('message', function(message) {
        //Escape HTML characters
        var data = message.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
        
        //Append message to the bottom of the list
        $('#comments').append('<li>' + data + '</li>');
        window.scrollBy(0, 10000000000);
        entry_el.focus();
      });
                     
      entry_el.keypress(function(event){
        //When enter is pressed send input value to node server
        if(event.keyCode != 13) return;
        var msg = entry_el.attr('value');
        if(msg){
           socket.emit('send_message', msg, function(data){
                console.log(data);
           });
        
        //Clear input value   
        entry_el.attr('value', '');
       }
      });
    });
  </script>
</head>
<body>
    <ul id="comments">
        {% for comment in Comments %}
            <li>{{comment.user}}: {{comment.text}}</li>
        {% endfor %}
    </ul>
    <input type="text" id="comment" name="comment" />
</body>
</html>

templates/navbar.html
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="{% block active_student %}{% endblock %}">
      <a href="{% url 'account:view_profile' %}?user_id={{ user.username }}">
        <img class="img-responsive img-thumbnail" src="{{ user.student.gravatar_url }}" /> {{ user.student.get_id }}
      </a>
    </li>
    {% if user.student.school %}
      <li class="{% block active_school %}{% endblock %}">
        <a href="{% url 'core:home' %}">
          <!--<img class="img-thumbnail" style="width:50" src="{{ user.student.school.logo_url }}" />-->
          <span class="glyphicon glyphicon-pencil"></span> {{ user.student.school }}
        </a>
      </li>
    {% endif %}
    <li class="{% block active_calendar %}{% endblock %}"><a href="{% url 'core:view_calendar' %}"><span class="glyphicon glyphicon-calendar"></span> Calendar</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    {% for study_group in user.student.study_group_set.all %}
      <li class="">
        <a href="{% url 'core:view_study_group' study_group.unique_id %}">
        {% if study_group.is_private %}
          <span class="glyphicon glyphicon-eye-close"></span> {{ study_group.name }}
        {% else %}
          <span class="glyphicon glyphicon-eye-open"></span> {{ study_group.name }}
        {% endif %}
        </a>
      </li>
    {% endfor %}
    <li class="col-xs-10 col-xs-offset-1 text-center">
      <button class="btn btn-sm btn-success btn-block"onclick="location.href='{% url 'core:create_study_group' %}'">Create group</button>
    </li>

    <li>
      <div class="footer">
        <div class="text-center">
          <div class="fb-like" data-href="http://gyutae.herokuapp.com/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
          <br />
          <br />
          Copyright © 2014 두 얼간이
        </div>
      </div>
    </li>
  </ul>
  <ul class="nav nav-sidebar">

  </ul>
</div>
 

templates/sub_navbar.html
<script type="text/javascript">
    function confirm_delete_study_group() {
      var conf= confirm('Are you sure to delete this study group');
      if (conf) {
        location.href='{% url 'core:delete_study_group' study_group_id=study_group.unique_id %}';
      }
    }
</script>
       <div class="col-sm-3 col-sm-offset-3 col-md-2 col-md-offset-2 sidebar inner-sidebar">
            <ul class="nav nav-list">
                <li class="nav-header text-center">
                  <h4><a href="{% url 'core:view_study_group' study_group.unique_id %}">{{ study_group.name }}</a></h4>
                </li>
                <!--<li class="nav-header"><a href="#">Users</a></li>-->
                {% for student in study_group.student_set.all %}
                  <li class="dropdown">
                    <a class="dropdown-toggle sub_nav_gravatar" href="#" data-toggle="dropdown"><img src="{{ student.gravatar_small_url }}" />
                      {{ student.get_id }}
                      {% if student in study_group.leader.all %}
                        <span class="glyphicon glyphicon-tower"></span>
                      {% endif %}
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      {% for event in student.assigned_to.all %}
                        {% if event in study_group.event_set.all %}
                          {% if event.study_group == study_group %}
                            <li>
                              {% if student in event.finished_student.all %}
                                {% if student == user.student %}
                                  <a href="{% url 'unfinish_event' study_group_id=study_group.unique_id event_id=event.id %}"><span class="glyphicon glyphicon-ok"></span> {{ event }}</a>
                                {% else %}
                                  <a href="#"><span class="glyphicon glyphicon-ok"></span> {{ event }}</a>
                                {% endif %}
                              {% else %}
                                {% if student == user.student %}
                                  <a href="{% url 'finish_event' study_group_id=study_group.unique_id event_id=event.id %}"><span class=""></span> {{ event }}</a>
                                {% else %}
                                  <a href="#"><span class=""></span> {{ event }}</a>
                                {% endif %}
                              {% endif %}
                            </li>
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                      <li><a href="{% url 'account:view_profile' %}?user_id={{ student.user.username }}">View profile</a></li>
                    </ul>
                  </li>
                {% endfor %}
                <li class="nav-header"><a href="{% url 'core:view_study_group' study_group_id=study_group.unique_id %}"><span class="glyphicon glyphicon-calendar"></span> Calendar</a></li>
                <li class="nav-header"><a href="{% url 'view_file_list' study_group_id=study_group.unique_id %}"><span class="glyphicon glyphicon-file"></span> File list</a></li>
              {% for board in study_group.board_set.all %}
                <!--<li class="dropdown">-->
                  <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ board }}<b class="caret"></b></a>-->
                  <li class="nav-header">{{ board }}</li>
                  <!--<ul class="dropdown-menu">-->
                    {% for post in board.post_set.all %}
                      <li><a href="{% url 'view_post' study_group_id=study_group.unique_id post_id=post.id board_id=board.id %}">{{ post.name }}</a></li>
                    {% endfor %}
                    {% if user.student in study_group.student_set.all %}
                      <li><a href="{% url 'create_post' study_group.unique_id board.id %}"><span class="glyphicon glyphicon-plus"></span> Add post</a></li>
                    {% endif %}
                  <!--</ul>-->
                <!--</li>-->
              {% endfor %}
              {% if user.student in study_group.student_set.all %}
                <li>
                  <button class="btn btn-sm btn-info btn-block" onclick="location.href='{% url 'create_board' study_group_id=study_group.unique_id %}'">Add Board</button>
                </li>
              {% endif %}
              <li>
                <form role="form" action="{% url 'core:join_study_group' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" value="{{ study_group.unique_id }}" name="group_unique_id">
                  {% if user.student not in study_group.student_set.all %}
                    <button class="btn btn-sm btn-primary btn-block delete-study-group-btn">Join study group</button>
                  {% else %}
                    <button class="btn btn-sm btn-warning btn-block delete-study-group-btn">Leave study group</button>
                  {% endif %}
                </form>
              </li>
              {% if user.student in study_group.leader.all %}
                <li>
                  <button class="btn btn-sm btn-danger btn-block delete-study-group-btn" onclick="confirm_delete_study_group()">Delete study group</button>
                </li>
              {% endif %}
            </ul>

          <!--Drop down version
          <ul class="nav nav-sidebar">
            {% for board in study_group.user_set.all %}
            {% endfor %}
            {% for board in study_group.board_set.all %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ board }}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  {% for post in board.post_set.all %}
                    <li><a href="#">{{ post.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            {% endfor %}
          <ul>-->
        </div>