account/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^follow/$', 'account.views.follow', name='follow'),

    url(r'^profile/$', 'account.views.view_profile', name='view_profile'),
    url(r'^sign_in/$', 'account.views.sign_in', name='sign_in'),
    url(r'^sign_up/$', 'account.views.sign_up', name='sign_up'),
    url(r'^sign_out/$', 'account.views.sign_out', name='sign_out'),
)

chat/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'chat.views.home', name='home'),
    url(r'^node_api$', 'chat.views.node_api', name='node_api'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

studyplan/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from core import views as c_views
from board import views as b_views
from event import views as e_views
from file import views as f_views

STUDY = r'^s/(?P<study_group_id>\w+)/'

BOARD = STUDY + r'board/'
EVENT = STUDY + r'event/'
FILE = STUDY + r'file/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'studyplan.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'core.views.index'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    #(r'^asset/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.ASSET_ROOT}),

    
    ###############
    # jfu
    ###############

    url(FILE + r'(?P<post_id>\d+)/upload/', f_views.upload, name = 'jfu_upload' ),
    url(FILE + r'(?P<post_id>\d+)/delete/(?P<pk>\d+)$', f_views.upload_delete, name = 'jfu_delete' ),
    url(FILE + r'/files/$', f_views.view_file_list, name = 'view_file_list' ),


    ###############
    # BOARD
    ###############

    url(BOARD + r'create/$', b_views.create_board, name='create_board'),

    url(BOARD + r'list/$', b_views.list_board, name='list_board'),
    url(BOARD + r'(?P<board_id>\d+)/create/$', b_views.create_post, name='create_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/edit/$', b_views.edit_post, name='edit_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/delete/$', b_views.delete_post, name='delete_post'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/$', b_views.create_comment, name='create_comment'),
    url(BOARD + r'(?P<board_id>\d+)/(?P<post_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', b_views.delete_comment, name='delete_comment'),

    url(BOARD + r'(?P<board_id>\d+)/view/(?P<post_id>\d+)$', b_views.view_post, name='view_post'),


    ###############
    # EVENT
    ###############

    url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),

    url(EVENT + r'get/$', e_views.get_event_as_json, name='get_event'),
    #url(EVENT + r'view/$', e_views.view_calendar, name='view_calendar'),
    url(EVENT + r'edit/$', e_views.edit_event, name='edit_event'),
    url(EVENT + r'delete/$', e_views.delete_event, name='delete_event'),
    url(EVENT + r'create/$', e_views.create_event, name='create_event'),

    #url(EVENT + r'finish/$', e_views.finish_event_as_json, name='finish_event'),
    #url(EVENT + r'unfinish/$', e_views.unfinish_event_as_json, name='unfinish_event'),

    url(EVENT + r'finish/(?P<event_id>\d+)/$', e_views.finish_event, name='finish_event'),
    url(EVENT + r'unfinish/(?P<event_id>\d+)/$', e_views.unfinish_event, name='unfinish_event'),


    ###############
    # CORE
    ###############

    url(r'^s/', include('core.urls', namespace='core')),

    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^account/', include('account.urls', namespace='account')),


    url(r'^chat/', include('chat.urls', namespace='chat')),

    (r'^summernote/', include('django_summernote.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

board/models.py
from django.db import models

from core.models import Student
from tag.models import Tag

# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=200)
    details = models.CharField(max_length=300)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Post(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField(blank=False)

    tag_set = models.ManyToManyField(Tag, blank=True, null=True)
    board = models.ForeignKey(Board, blank=True, null=True)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    viewed_student = models.ManyToManyField(Student, blank=True, null=True, related_name='viewed_student')

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    content = models.TextField(blank=False)

    post = models.ForeignKey(Post, blank=True, null=True)

    creator = models.ForeignKey(Student)
    created_at  = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.content

file/models.py
from django.db import models
from django.core.files import File
from django.core.files.storage import FileSystemStorage

from core.models import Student
from board.models import Board, Post

fs = FileSystemStorage(location='media')
upload_to='media'

# Create your models here.
class File(models.Model):
    file_field = models.FileField(upload_to=upload_to, default = None, blank=True)
    slug = models.SlugField(max_length=50, blank=True)

    post = models.ForeignKey(Post, blank=True, null=True)
    uploader = models.ForeignKey(Student, blank=True, null=True)

    def __unicode__(self):
        return self.file_field.name.replace(upload_to+'/','')

    def get_full_path(self):
        return 'media/' + self.file_field.name

board/forms.py
#-*- coding: utf-8 -*-
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from .models import Post, Board, Comment
from core.models import StudyGroup
from account.models import Student
from tag.models import Tag

class BoardForm(forms.ModelForm):
    name = forms.CharField(label="Board name")
    details = forms.CharField(label="Details", widget=forms.Textarea)

    class Meta:
        model = Board
        fields = ['name', 'details']

    def __init__(self, user=None, study_group=None , *args, **kwargs):
        self._user = user
        self._study_group = study_group
        super(BoardForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        form = super(BoardForm, self).is_valid()

        return form

    def save(self, commit=True):
        if not self._user:
            return None

        board = Board(name = self.cleaned_data["name"],
                      details = self.cleaned_data["details"],
                      creator = Student.objects.get(user=self._user))
        board.save()

        self._study_group.board_set.add(board)
        self._study_group.save()

        #if commit:
        #    group.save()

        return board

class PostForm(forms.ModelForm):
    name = forms.CharField(label="Post name")
    content = forms.CharField(widget=SummernoteWidget(), help_text='사진은 드래그 앤 드롭으로 첨부 가능합니다 :)')
    
    tag_set = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False)
 
    class Meta:
        model = Post
        fields = ['name', 'content', 'tag_set']

    def __init__(self, user=None, board_id=None, post_id=None, *args, **kwargs):
        self._user = user

        if board_id:
            self._board = Board.objects.get(id=board_id)

        if post_id:
            self._post = Post.objects.get(id=post_id)

        super(PostForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        form = super(PostForm, self).is_valid()

        return form

    def save(self, commit=True):
        try:
            self._post.name = self.cleaned_data["name"]
            self._post.content = self.cleaned_data["content"]

            self._post.tag_set.all().delete()
            for tag in self.cleaned_data["tag_set"]:
                self._post.tag_set.add(tag)

            self._post.save()

            return self._post
        except:
            pass

        if not self._user:
            return None

        post = Post(name = self.cleaned_data["name"],
                    content = self.cleaned_data["content"],
                    creator = Student.objects.get(user=self._user))
        post.save()

        for tag in self.cleaned_data["tag_set"]:
            post.tag_set.add(tag)

        post.save()

        try:
            self._board.post_set.add(post)
        except:
            pass

        #if commit:
        #    group.save()

        return post


class CommentForm(forms.ModelForm):
    #content = forms.CharField(widget=SummernoteWidget())
    content = forms.CharField(widget=forms.Textarea(attrs={'width': '100%', 'cols': 80, 'rows': 5}))
    
    class Meta:
        model = Post
        fields = ['content']

    def __init__(self, user=None, post_id=None, *args, **kwargs):
        self._user = user
        self._post = Post.objects.get(id=post_id)
        super(CommentForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        form = super(CommentForm, self).is_valid()
        return form

    def save(self, commit=True):
        if not self._user:
            return None

        comment = Comment(content = self.cleaned_data["content"].replace('\r\n','<br />'),
                          creator = Student.objects.get(user=self._user))
        comment.save()

        self._post.comment_set.add(comment)

        #if commit:
        #    group.save()

        return comment

board/views.py
from django.shortcuts import render, redirect, render_to_response, RequestContext, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from .forms import BoardForm, PostForm, CommentForm
from .models import Post, Comment
from core.models import StudyGroup

import sys
from utils.func import *

########################
# List board
########################

@login_required
def list_board(request):
    form = BoardForm(data=request.POST or None, user=request.user)

    context = RequestContext(request)
    template = 'core/create_board.html'

    if request.method == "POST":
        if form.is_valid():
            board = form.save(commit=False)
            board.save()

            return HttpResponseRedirect(reverse('core:view_study_group', kwargs={'study_group_id':study_group_id,}))
        else:
            return create_board_view(request)

    return create_board_view(request)

########################
# View post
########################

@login_required
def view_post(request, study_group_id, post_id, board_id=None):
    form = CommentForm(data=request.POST or None, user=request.user, post_id=post_id)

    context = RequestContext(request)
    template = 'board/view_post.html'

    study_group = StudyGroup.objects.get(unique_id=study_group_id)
    current_student = get_student_from_user(request.user)

    try:
        post = Post.objects.get(id=post_id)

        for comment in post.comment_set.all():
            comment.content = comment.content.replace('\r\n','<br />')

        if current_student in study_group.student_set.all():
            if current_student not in post.viewed_student.all():
                post.viewed_student.add(current_student)

        return render(request, template, {'form': form, 'study_group': study_group,'post': post, 'board_id': post.board.id, 'user': request.user})

    except:
        for e in sys.exc_info():
            print e
        return HttpResponseRedirect(reverse('core:view_study_group', kwargs={'study_group_id':study_group_id,}))


########################
# Create comment
########################

@login_required
def create_comment(request, study_group_id, post_id, board_id=None):
    form = CommentForm(data=request.POST or None, user=request.user, post_id=post_id)
    context = RequestContext(request)

    if request.method == "POST":
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

########################
# Delete comment
########################

@login_required
def delete_comment(request, study_group_id=None, board_id=None, comment_id=None, post_id=None):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()

    if study_group_id == '0':
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
    else:
        return HttpResponseRedirect(reverse('view_post', kwargs={'study_group_id':study_group_id, 'board_id':board_id, 'post_id': post_id, }))


########################
# Create board
########################

@login_required
def create_board(request, study_group_id):
    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    form = BoardForm(data=request.POST or None, user=request.user, study_group=study_group)

    context = RequestContext(request)
    template = 'core/create_board.html'

    if request.method == "POST":
        if form.is_valid():
            board = form.save(commit=False)
            board.save()

            return HttpResponseRedirect(reverse('core:view_study_group', kwargs={'study_group_id':study_group_id,}))
        else:
            return create_board_view(request, study_group)

    return create_board_view(request, study_group)

@login_required
def create_board_view(request, study_group):
    form = BoardForm(data=request.POST or None, user=request.user, study_group=study_group)
    template = 'board/create_board.html'

    return render(request, template, {'form': form, 'study_group': study_group})

########################
# Create post
########################

@login_required
def create_post(request, study_group_id=None, board_id=None):
    form = PostForm(data=request.POST or None, user=request.user, board_id=board_id)

    context = RequestContext(request)
    template = 'core/create_post.html'

    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.method == "POST":
        if form.is_valid():
            post = form.save(commit=False)
            post.save()

            return HttpResponseRedirect(reverse('core:view_study_group', kwargs={'study_group_id':study_group_id,}))
        else:
            return create_post_view(request, study_group, board_id)

    return create_post_view(request, study_group, board_id)

@login_required
def create_post_view(request, study_group, board_id):
    form = PostForm(data=request.POST or None, user=request.user, board_id=board_id)
    template = 'board/create_post.html'

    return render(request, template, {'form': form, 'study_group': study_group, 'board_id': board_id})

########################
# Edit post
########################

@login_required
def edit_post(request, study_group_id=None, board_id=None, post_id=None):
    instance = Post.objects.get(id=post_id)
    form = PostForm(data=request.POST or None, user=request.user, instance=instance, post_id=post_id)

    context = RequestContext(request)
    template = 'core/create_post.html'

    study_group = StudyGroup.objects.get(unique_id=study_group_id)

    if request.method == "POST":
        print "!@#!@#"
        if form.is_valid():
            print "!@#!@#"
            post = form.save()
            #post.save()

            return HttpResponseRedirect(reverse('core:view_study_group', kwargs={'study_group_id':study_group_id,}))
        else:
            return edit_post_view(request, study_group, board_id, post_id)

    return edit_post_view(request, study_group, board_id, post_id)

########################
# Delete post
########################

@login_required
def delete_post(request, study_group_id=None, board_id=None, post_id=None):
    instance = Post.objects.get(id=post_id)
    instance.delete()

    return HttpResponseRedirect(reverse('core:view_study_group', kwargs={'study_group_id':study_group_id,}))

@login_required
def edit_post_view(request, study_group, board_id, post_id):
    instance = Post.objects.get(id=post_id)
    form = PostForm(data=request.POST or None, user=request.user, instance=instance, post_id=post_id)

    template = 'board/create_post.html'

    return render(request, template, {'form': form, 'study_group': study_group, 'board_id': board_id, 'post_id': post_id})

templates/board/create_board.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}

        {% include "sub_navbar.html" %}

        <div class="col-sm-6 col-sm-offset-6 col-md-8 col-md-offset-4 main">
          <form class="form-signin" role="form" action="{% url 'create_board' study_group_id=study_group.unique_id %}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ next_url }}" name="next_url">
            <button class="btn btn-lg btn-success btn-block" type="submit">Create board</button>
          </form>
        </div>
      </div>
    </div>

{% endblock %}

templates/board/create_post.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}

        {% include "sub_navbar.html" %}

        <div class="col-sm-6 col-sm-offset-6 col-md-8 col-md-offset-4 main">
          {% if post_id %}
            <form class="form-horizontal" role="form" action="{% url 'edit_post' study_group_id=study_group.unique_id board_id=board_id post_id=post_id %}" method="post"> {% csrf_token %}
              {{ form.as_p }}
              <input type="hidden" value="{{ next_url }}" name="next_url">
              <button class="btn btn-lg btn-success btn-block" type="submit">Edit post</button>
          {% else %}
            <form class="form-horizontal" role="form" action="{% url 'create_post' study_group_id=study_group.unique_id board_id=board_id %}" method="post"> {% csrf_token %}
              {{ form.as_p }}
              <input type="hidden" value="{{ next_url }}" name="next_url">
              <button class="btn btn-lg btn-success btn-block" type="submit">Create post</button>
          {% endif %}
          </form>

        </div>
      </div>
    </div>


{% endblock %}

templates/board/view_board.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}

    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}

        <div class="col-sm-3 col-sm-offset-3 col-md-2 col-md-offset-2 sidebar inner-sidebar">
            <ul class="nav nav-list">
            {% for board in study_group.user_set.all %}
            {% endfor %}
            {% for board in study_group.board_set.all %}
              <!--<li class="dropdown">-->
                <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ board }}<b class="caret"></b></a>-->
                <li class="nav-header">{{ board }}</li>
                <!--<ul class="dropdown-menu">-->
                  {% for post in board.post_set.all %}
                    <li><a href="{% url 'board:view_post' study_group.unique_id post.id %}">{{ post.name }}</a></li>
                  {% endfor %}
                    <li><a href="{% url 'board:view_post' study_group.unique_id post.id %}"><span class="glyphicon glyphicon-plus"></span>{{ post.name }}</a></li>
                <!--</ul>-->
              <!--</li>-->
            {% endfor %}
            </ul>

          <!--Drop down version
          <ul class="nav nav-sidebar">
            {% for board in study_group.user_set.all %}
            {% endfor %}
            {% for board in study_group.board_set.all %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ board }}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  {% for post in board.post_set.all %}
                    <li><a href="#">{{ post.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            {% endfor %}
          <ul>-->
        </div>
 
        <div class="col-sm-6 col-sm-offset-6 col-md-8 col-md-offset-4 main">
          <h4>{{ post }}</h4>

          {{ post.content }}
        </div>
      </div>
    </div>

{% endblock %}

templates/board/view_post.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content_with_nav %}
  <script type="text/javascript"> 
    function confirm_delete_post() {
      var conf= confirm('Are you sure to delete this post');
      if (conf) {
        location.href='{% url 'delete_post' study_group_id=study_group.unique_id board_id=board_id post_id=post.id %}';
      }
    }
    function confirm_delete_comment(comment_id) {
      var conf= confirm('Are you sure to delete this comment');
      if (conf) {
        location.href='/s/{{ study_group.unique_id }}/board/{{ board_id }}/{{ post.id }}/comment/' + comment_id + '/delete/';
      }
    }
  </script>
    <div class="container-fluid">
      <div class="row">
        {% include "navbar.html" %}
        {% include "sub_navbar.html" %}

        <div class="col-sm-6 col-sm-offset-6 col-md-8 col-md-offset-4 main">
          {% if post.creator.user == user %}
            <button type="button" class="btn btn-warning btn-lg pull-right" onclick='confirm_delete_post();'">
              <span class="glyphicon glyphicon-trash"></span> Delete post
            </button>
            <button type="button" class="btn btn-info btn-lg pull-right edit-post-btn" onclick="location.href='{% url 'edit_post' study_group_id=study_group.unique_id board_id=board_id post_id=post.id %}'">
              <span class="glyphicon glyphicon-edit"></span> Edit post
            </button>
          {% endif %}

          <h2>{{ post }}</h2>
          <p>작성자 :
          <a href="{% url 'account:view_profile' %}?user_id={{ post.creator.user.username }}">
            {% if post.creator == user.student %}
              <span class="badge badge-me">{{ post.creator.get_id }}</span></a>
            {% elif post.creator in user.student.friends.all %}
              <span class="badge badge-friend">{{ post.creator.get_id }}</span></a>
            {% else %}
              <span class="badge">{{ post.creator.get_id }}</span></a>
            {% endif %}

           | {{ post.created_at }}</p>
          <p>본 사람 : 

          {% for student in post.viewed_student.all %}
            <a href="{% url 'account:view_profile' %}?user_id={{ student.user.username }}">
            {% if student == user.student %}
              <span class="badge badge-me">{{ student.get_id }}</span></a>, 
            {% elif student in user.student.friends.all %}
              <span class="badge badge-friend">{{ student.get_id }}</span></a>, 
            {% else %}
              <span class="badge">{{ student.get_id }}</span></a>, 
            {% endif %}
          {% endfor %}
          </p>

          <div class="well">
            <h4>Content</h4>
            {{ post.content | safe }}
          </div>

          <div class="well" style="margin-top:20px;">
            <ul class="list-group">
              <li href="#" class="list-group-item active">
                <strong style="color:white;">Uploaded file</strong>
                <span class="badge">{{ post.file_set.all | length }}</span>
              </li>
              {% for file in post.file_set.all %}
              <li class="list-group-item">
                <a href="{% url 'account:view_profile' %}?user_id={{ file.uploader.user.username }}">
                {% if file.uploader == user.student %}
                  <span class="badge badge-me pull-right">{{ file.uploader.get_id }}</span></a>
                {% elif file.uploader in user.student.friends.all %}
                  <span class="badge badge-friend pull-right">{{ file.uploader.get_id }}</span></a>
                {% else %}
                  <span class="badge pull-right">{{ file.uploader.get_id }}</span></a>
                {% endif %}
                <a href="{{ file.file_field.url }}">{{ file }}</a>
              </li>
              {% endfor %}
            </ul>

            {% if user.student in study_group.student_set.all %}
              <div class="well">
                  {% load jfutags %}
                  {% jfu 'file/upload.html' study_group_id=study_group.unique_id post_id=post.id %}
                <div class="block text-center">
                  <p class="helptext">드래그 앤 드롭으로 첨부 가능 :)</p>
                </div>
              </div>
            {% endif %}
          </div>

          <div class="">
            <h3>Comments </h3>

            {% for comment in post.comment_set.all %}
            <div class="well">
              {% if comment.creator.user == user %}
                <div class="pull-right">
                  <button type="button" class="btn btn-warning btn-sm" onclick="confirm_delete_comment({{ comment.id }})"/>Delete</button>
                </div>
                <div class="pull-right">
                  <button type="button" class="btn btn-info btn-sm comment-edit-btn"/>Edit</button>
                </div>
              {% endif %}
              <div class="pull-left">
                <a href="{% url 'account:view_profile' %}?user_id={{ comment.creator.user.username }}">
                  <img class="img-responsive img-thumbnail comment-thumbnail" src="{{ comment.creator.gravatar_middle_url }}">
                </a>
              </div>
              <div class="comment-content">
                <div class="comment-author">
                  <a href="{% url 'account:view_profile' %}?user_id={{ comment.creator.user.username }}">
                  {% if comment.creator == user.student %}
                    <span class="badge badge-me">{{ comment.creator.get_id }}</span></a>
                  {% elif comment.creator in user.student.friends.all %}
                    <span class="badge badge-friend">{{ comment.creator.get_id }}</span></a>
                  {% else %}
                    <span class="badge">{{ comment.creator.get_id }}</span></a>
                  {% endif %}

                  <small>{{ comment.created_at }}</small>
                </div>

                <div class="comment-text">
                  {{ comment.content | safe }}
                </div>
              </div>
            </div>
            {% endfor %}

            {% if user.student in study_group.student_set.all %}
              <form class="form-comment" role="form" action="{% url 'create_comment' study_group_id=study_group.unique_id board_id=board_id post_id=post.id %}" method="post"> {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" value="{{ next_url }}" name="next_url">
                <button class="btn btn-sm btn-success btn-block" style="margin-bottom: 30px;" type="submit">Write comment</button>
              </form>
            {% endif %}
          </div>

        </div>
      </div>
    </div>

{% endblock %}